kind = "web"
previewPath = "/"
title = "Estude Loterias"
version = "1.0.0"
id = "artifacts/estude-loterias"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23948

[services.development]
run = "pnpm --filter @workspace/estude-loterias run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/estude-loterias", "run", "build" ]
publicDir = "artifacts/estude-loterias/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23948"
BASE_PATH = "/"
